### PR TITLE
Add clang-toolchain image

### PR DESCRIPTION
**Pull request by d**
This is a very simple image that supplies clang-format, git, and
parallel to facilitate running clang-format checks in CI. This also lays
the foundation for running clang-tidy if we need to in the future.

Also added is configuration to test, build, and push in Concourse.

Steps to locally run tests are documented in README.

For a sample pipeline, see https://qpa.ci.gpdb.pivotal.io/teams/main/pipelines/qp-images

### CODE REVIEW

**Comment by d** [comment]
Note to reviewers: the last commit is for exposition purpose only, and should be dropped before merging

**Comment by chrishajas** [comment]
Is the idea here that we have a separate image that runs clang format? Mostly thinking that this is another image to maintain by us vs doing this within the existing build images.

**Comment by d** [comment]
> Is the idea here that we have a separate image that runs clang format? Mostly thinking that this is another image to maintain by us vs doing this within the existing build images.

Yes!

Because clang-format is a dev dependency, not a dependency that we ship (say linked). The thinking here is if I also plan to propose changes in the future that will be enforced by `clang-tidy` (use `override` for example) and that's where the idea of having a single-purpose dev image becomes useful

**Review by chrishajas — APPROVED** [review]
LGTM, but we need to make sure this knowledge is spread throughout the team, otherwise it might not be maintained. I never knew this repo existed, and it hasn't been modified in 3 years.

**Comment by d** [comment]
I agree. Other than README, do you identify other knowledge gaps that I should follow up on?

**Comment by chrishajas** [comment]
> I agree. Other than README, do you identify other knowledge gaps that I should follow up on?

I think having others review this would be good if they don't know this already.

**Comment by d** [comment]
> > I agree. Other than README, do you identify other knowledge gaps that I should follow up on?
> 
> I think having others review this would be good if they don't know this already.

OK, pinning the dropped commit https://github.com/Pivotal-DataFabric/qp-images/commit/751baf8d48cd7d709e882a8eef90fea41d17af40 for posterity

**Pull request merged**
